# Action limits
ACTION_LOW = [-0.5, -0.3]
ACTION_HIGH = [0.5, 0.6]

# Vehicle
MAX_VELOCITY = 30.0

# Episode limits
MAX_EPISODE_STEPS = 5000
MAX_LOST_LINE_STEPS = 300

# Stuck detection
STUCK_STEP_LIMIT = 500
STUCK_DISTANCE_THRESHOLD = 0.001

# Obstacle distances
OBSTACLE_NEAR_DISTANCE = 10.0
OBSTACLE_CLOSE_DISTANCE = 6.0
OBSTACLE_VERY_CLOSE_DISTANCE = 4.0
COLLISION_DISTANCE = 1.1

# Line detection
LINE_SIDE_THRESHOLD = 0.15
LINE_CENTER_THRESHOLD = 0.15
RECOVERY_CENTER_THRESHOLD = 0.25

# Normal lane following rewards
CENTER_REWARD_WEIGHT = 0.35
FORWARD_REWARD_WEIGHT = 0.12
LANE_ERROR_PENALTY = 0.30
STEERING_SMOOTHNESS_PENALTY = 0.04
CENTERED_LINE_BONUS = 0.20

# Obstacle avoidance rewards
AVOIDANCE_STEERING_REWARD = 0.35
AVOIDANCE_WRONG_STEERING_PENALTY = 0.35
AVOIDANCE_LINE_CENTER_WEIGHT = 0.05
AVOIDANCE_FORWARD_REWARD = 0.05

# Speed control near obstacle
OBSTACLE_SPEED_PENALTY = 0.30
OBSTACLE_SLOW_SPEED_TARGET = 0.35
OBSTACLE_SLOW_SPEED_REWARD = 0.20

# Very close obstacle
VERY_CLOSE_OBSTACLE_PENALTY = 0.70
VERY_CLOSE_SPEED_PENALTY = 0.30

# Recovery rewards
RECOVERY_SAME_SIDE_BONUS = 0.45
RECOVERY_CENTER_BONUS = 0.45
RECOVERY_PARTIAL_BONUS = 0.20
RECOVERY_LINE_LOST_PENALTY = 0.10
RECOVERY_STEERING_REWARD = 0.25
RECOVERY_WRONG_STEERING_PENALTY = 0.25
RECOVERY_SPEED_PENALTY = 0.10
RECOVERY_NO_SIDE_STEERING_REWARD = 0.10

# General penalties
LINE_LOST_PENALTY = 0.40
LINE_LOST_SPEED_PENALTY = 0.15
REVERSE_PENALTY = 0.10
STEP_PENALTY = 0.005
LOST_LINE_DONE_PENALTY = 1.0
STUCK_DONE_PENALTY = 1.0
COLLISION_PENALTY = 1.0


# Lane following steering rewards
LANE_STEERING_REWARD = 0.20
LANE_WRONG_STEERING_PENALTY = 0.30
LANE_LOW_STEERING_PENALTY = 0.20
LANE_HIGH_ERROR_SPEED_PENALTY = 0.20

# Recovery scaling
RECOVERY_CENTER_WEIGHT = 0.40

# Critical dynamic obstacle
CRITICAL_MAX_NOT_STOPPED_STEPS = 250

CRITICAL_FULL_STOP_SPEED_THRESHOLD = 0.005
CRITICAL_FORWARD_THROTTLE_THRESHOLD = 0.05

# Critical stop rewards and penalties
CRITICAL_STOP_REWARD = 0.30
CRITICAL_NOT_STOPPED_PENALTY = 0.20
CRITICAL_FORWARD_PENALTY_WEIGHT = 0.35

CRITICAL_STOPPED_WITH_THROTTLE_PENALTY = 0.20

CRITICAL_RESUME_FORWARD_REWARD = 0.12
CRITICAL_UNNECESSARY_STOP_PENALTY = 0.20

CRITICAL_FAILED_TO_STOP_PENALTY = 1.0
CRITICAL_COLLISION_PENALTY = 1.0

# Inactivity penalties and rewards
# Tuned to force the agent to resume movement after the obstacle clears

# Minimum expected movement per step when there is no obstacle
CRITICAL_INACTIVE_MIN_MOVEMENT = 0.015

# Strong penalty for not moving
CRITICAL_INACTIVE_LOW_MOVEMENT_PENALTY = 0.60

# Strong penalty for not applying throttle
CRITICAL_INACTIVE_NO_THROTTLE_PENALTY = 0.40

# Bonus for positive throttle
CRITICAL_INACTIVE_FORWARD_BONUS_WEIGHT = 0.35

# Penalty for unnecessary reverse movement
CRITICAL_INACTIVE_REVERSE_PENALTY_WEIGHT = 0.45

# One-time resume bonus when the obstacle disappears
CRITICAL_RESUME_BONUS = 0.80

CRITICAL_ACTIVE_FORWARD_PENALTY_BASE = 0.35
CRITICAL_ACTIVE_FORWARD_PENALTY_WEIGHT = 0.45
CRITICAL_ACTIVE_REVERSE_PENALTY_BASE = 0.15
CRITICAL_ACTIVE_REVERSE_PENALTY_WEIGHT = 0.20
CRITICAL_ACTIVE_STEERING_PENALTY_WEIGHT = 0.35
CRITICAL_ACTIVE_MOVEMENT_PENALTY_WEIGHT = 0.80
CRITICAL_ACTIVE_STOPPED_BONUS = 0.20
CRITICAL_ACTIVE_STEERING_THRESHOLD = 0.05
