# Action limits
ACTION_LOW = [-0.5, -0.3]
ACTION_HIGH = [0.5, 0.6]

# Vehicle
MAX_VELOCITY = 30.0

# Episode limits
MAX_EPISODE_STEPS = 5000
MAX_LOST_LINE_STEPS = 300

# Stuck detection
STUCK_STEP_LIMIT = 500
STUCK_DISTANCE_THRESHOLD = 0.001

# Obstacle distances
OBSTACLE_NEAR_DISTANCE = 10.0
OBSTACLE_CLOSE_DISTANCE = 6.0
OBSTACLE_VERY_CLOSE_DISTANCE = 3.0
COLLISION_DISTANCE = 2.0

# Line detection
LINE_SIDE_THRESHOLD = 0.15
LINE_CENTER_THRESHOLD = 0.15
RECOVERY_CENTER_THRESHOLD = 0.25

# Normal lane following rewards
CENTER_REWARD_WEIGHT = 4.0
FORWARD_REWARD_WEIGHT = 0.8
LANE_ERROR_PENALTY = 2.0
STEERING_SMOOTHNESS_PENALTY = 0.2
CENTERED_LINE_BONUS = 2.0

# Obstacle avoidance rewards
AVOIDANCE_STEERING_REWARD = 4.0
AVOIDANCE_WRONG_STEERING_PENALTY = 3.0
AVOIDANCE_LINE_CENTER_WEIGHT = 0.3
AVOIDANCE_FORWARD_REWARD = 0.2

# Speed control near obstacle
OBSTACLE_SPEED_PENALTY = 3.0
OBSTACLE_SLOW_SPEED_TARGET = 0.35
OBSTACLE_SLOW_SPEED_REWARD = 2.0

# Very close obstacle
VERY_CLOSE_OBSTACLE_PENALTY = 5.0
VERY_CLOSE_SPEED_PENALTY = 2.0

# Recovery rewards
RECOVERY_SAME_SIDE_BONUS = 6.0
RECOVERY_CENTER_BONUS = 4.0
RECOVERY_PARTIAL_BONUS = 2.0
RECOVERY_LINE_LOST_PENALTY = 0.2
RECOVERY_STEERING_REWARD = 2.0
RECOVERY_WRONG_STEERING_PENALTY = 1.5
RECOVERY_SPEED_PENALTY = 0.5
RECOVERY_NO_SIDE_STEERING_REWARD = 0.5

# General penalties
LINE_LOST_PENALTY = 2.0
LINE_LOST_SPEED_PENALTY = 0.5
REVERSE_PENALTY = 0.5
STEP_PENALTY = 0.01
LOST_LINE_DONE_PENALTY = 20.0
STUCK_DONE_PENALTY = 20.0
COLLISION_PENALTY = 25.0